import { execSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const buildVerificationPath = join(root, "docs", "BUILD_VERIFICATION.md");

const checks = [
  { label: "npm run lint", cmd: "npm run lint" },
  { label: "npm run build", cmd: "npm run build" },
  { label: "npm run check:routes", cmd: "npm run check:routes" },
];

const rows = [];
let overallPass = true;
const MAX_NOTE_LINES = 3;

function runCheck(check) {
  let status = "pass";
  let output = "";
  try {
    output = execSync(check.cmd, { encoding: "utf8", stdio: "pipe" });
  } catch (error) {
    status = "fail";
    overallPass = false;
    output = (error.stdout ? error.stdout.toString() : "") + (error.stderr ? error.stderr.toString() : "");
    if (!output.trim()) {
      output = error.message ?? "Command failed without output.";
    }
  }

  const summary = getSummaryLine(status, output);
  rows.push({
    label: check.label,
    status,
    summary,
  });

  return { status, output };
}

function getSummaryLine(status, output) {
  const lines = output.split("\n").map((line) => line.trim()).filter(Boolean);
  if (lines.length === 0) {
    return "No command output";
  }

  if (status === "pass") {
    return lines[0];
  }

  const errorHints = [
    "FATAL",
    "ERROR",
    "Build error occurred",
    "Next.js build worker exited with code",
    "Failed to write app endpoint",
    "Turbopack",
  ];
  const hints = lines.filter((line) =>
    errorHints.some((hint) => line.includes(hint)),
  );
  const summaryLines = (hints.length ? hints : lines.slice(-MAX_NOTE_LINES)).slice(
    0,
    MAX_NOTE_LINES,
  );

  return sanitizeSummary(summaryLines.join(" | "));
}

function sanitizeSummary(text) {
  return text
    .replaceAll(/\u001b\[[0-9;]*m/g, "")
    .replaceAll("|", "\\|");
}

function getCommitSha() {
  try {
    return execSync("git rev-parse HEAD", { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

const runAt = new Date().toISOString();
const commitSha = getCommitSha();
const knownFailures = [];

for (const check of checks) {
  const { status, output } = runCheck(check);
  if (status === "fail" && output) {
    knownFailures.push(
      `- ${check.label}: ${getSummaryLine(status, output)}`,
    );
  }
}

if (!existsSync(buildVerificationPath)) {
  writeFileSync(
    buildVerificationPath,
    `# Build Verification\n\nDate: ${runAt}\n\n`,
    "utf8",
  );
}

const statusRows = rows
  .map(
    (row) =>
      `| ${row.status.toUpperCase()} | ${row.label} | ${row.summary.replaceAll("|", "\\|")} |`,
  )
  .join("\n");

const report = `# Build Verification\n\nDate: ${runAt}\n\nCommit SHA: ${commitSha}\n\n## Result\n\n` +
  `Overall release verification: ${overallPass ? "PASS" : "FAIL"}\n\n` +
  `## Command Results\n\n| Result | Command | Note |\n| --- | --- | --- |\n${statusRows}\n\n` +
  `## Known Failures\n\n` +
  `${overallPass ? "- None" : knownFailures.join("\n")}\n\n` +
  "## Notes\n\nGenerated by `npm run verify:release`.\n";

writeFileSync(buildVerificationPath, report, "utf8");

if (!overallPass) process.exit(1);
